### ISSUE TITLE
CSS Positioning Blog Post

### ISSUE THREAD

**Issue by annewchen** [anaclair/anaclair.github.io#10]
Hello~
Your website has a great style - simple and elegant. Since all of your pages have the same stylesheet it makes loading each page seem instantaneous.
The issue I found was with your CSS positioning blog post. It was a great idea to have working examples built into your page. The only problem with this is your text for the fixed and absolute examples are hard to read. If you can make the absolute and static blocks relatively transparent, I believe the absolute block would become readable. As for the fixed block, it is so far right that it is cut off. If you can give it a right margin, it would be perfect. Good luck on your website, I look forward to seeing how it will progress from here :)

**Comment by anaclair** [comment]
Anne, thank you for this feedback!

I really appreciate that you took the time. :) I did a little
re-positioning with your feedback in mind. If you have a free moment, let
me know if the post is more readable. I'll continue to work on improving
it...

http://anaclair.github.io/blog/t2-css-design.html

Thanks again for your help! I like your website, too, it's fun and
cheerful. Hey, we both have a purple background. [?]

Best!

**Comment by annewchen** [comment]
Hi Ana,
Just checked again and everything it readable. I checked on both my computer and cellphone so you should be all set!
I have a fondness for purple as well :D 
Looking forward to seeing your website throughout DBC!

**Comment by anaclair** [comment]
Thanks, Anne! Likewise. :D
